name: "rustfull"
services:
  psql:
    image: postgres:16
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rustfull
    ports:
      - "5432:5432"
    expose:
      - 5432
  rust:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
        PROJECT_NAME: rustfull
        TARGET_ARCHITECTURE: x86_64
        # release-superopt creates a more optimized build than release-opt but might
        # take significantly longer since it uses fat lto and only a single build thread
        PROFILE: release-superopt
    ports:
      - "3001:7878"
    environment:
      DATABASE_URL: "postgres://root:root@psql/rustfull"

volumes:
  database:
